### ISSUE TITLE
read_dimensions needs empty DDF error message

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#569]
If a DDF was not created properly its internal structure will not be as expected. Normally this also means that the file size is `0 KB`.

In those situations when attempting `read_dimensions()` the following traceback will be produced:

```python
Traceback (most recent call last):
  File "dim-qp-sav.py", line 14, in <module>
    meta, data = read_dimensions(path_mdd, path_ddf)
  File "C:\Anaconda2\lib\site-packages\quantipy\core\tools\dp\io.py", line 296, in read_dimensions
    meta, data = quantipy_from_dimensions(path_mdd, path_ddf)
  File "C:\Anaconda2\lib\site-packages\quantipy\core\tools\dp\dimensions\reader.py", line 808, in quantipy_from_dimensions
    ddf, levels = quantipy_clean(ddf_to_pandas(path_ddf))
  File "C:\Anaconda2\lib\site-packages\quantipy\core\tools\dp\dimensions\reader.py", line 65, in ddf_to_pandas
    sql['Levels'].set_index(['TableName'], drop=True, inplace=True)
KeyError: 'Levels'
```

The problem manifests as `KeyError: 'Levels'` because the DDF is missing a table called 'Levels', which should always be there if the file is not corrupted.

What would be better is to catch this and provide a more user friendly error such as `Can't find Levels, your DDF may be empty or corrupt`.

**Comment by jamesrkg** [comment]
Resolved by #570.
