### ISSUE TITLE
read_dimensions returns value error.

### ISSUE THREAD

**Issue by bsthinker** [Quantipy/quantipy#994]
I have the following program

import pandas as pd
import numpy as np
import quantipy as qp

meta, data = qp.read_dimensions('final.mdd', 'final.ddf')

When I run the program, I get the following error message.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f374a7ccda34> in <module>()
      3 import quantipy as qp
      4 
----> 5 meta, data = qp.read_dimensions('final.mdd', 'final.ddf')

/home/brent/quantipy/quantipy/quantipy/core/tools/dp/io.pyc in read_dimensions(path_mdd, path_ddf)
    294 def read_dimensions(path_mdd, path_ddf):
    295 
--> 296     meta, data = quantipy_from_dimensions(path_mdd, path_ddf)
    297     return meta, data
    298 

/home/brent/quantipy/quantipy/quantipy/core/tools/dp/dimensions/reader.pyc in quantipy_from_dimensions(path_mdd, path_ddf, fields, grids)
    856 def quantipy_from_dimensions(path_mdd, path_ddf, fields='all', grids=None):
    857 
--> 858     ddf, levels = quantipy_clean(ddf_to_pandas(path_ddf))
    859     L1 = ddf['HDATA'].copy()
    860     L1.drop('LevelId_HDATA', axis=1, inplace=True)

/home/brent/quantipy/quantipy/quantipy/core/tools/dp/dimensions/reader.pyc in quantipy_clean(ddf)
    144             while True:
    145                 parent = ddf['Levels'].loc[child,'ParentName']
--> 146                 if parent=='None':
    147                     break
    148                 id = 'id_'+parent

/home/brent/.local/lib/python2.7/site-packages/pandas/core/generic.pyc in __nonzero__(self)
    915         raise ValueError("The truth value of a {0} is ambiguous. "
    916                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
--> 917                          .format(self.__class__.__name__))
    918 
    919     __bool__ = __nonzero__

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Here are my installation steps.
Installed on Ubuntu 17
1) Install Anaconda2.and update after installation
2) Clone Quantipy repository 
3) set up and activate a virtual environment
4) pip install step.

I am able to run a test script on the CSV files.  But not the DDF.  Any help would be appreciated,

**Comment by alextanski** [comment]
Hi @bsthinker! 

Are you running on the `develop` branch of Quantipy (not sure though if that would fix it if you aren't)? Any chance you could provide us with the ddf/mdd you're using (or a reduced toy example  from that)?

Is only that one failing or can't you convert from any Dimensions sources?

@jamesrkg Let's look at this next week!

**Comment by bsthinker** [comment]
I'm using the master branch on git hub.  How/what do I do to select a different version?  I will test other MDDs/DDFs. If I still have problems, I will look at getting a suitable data file to you.

**Comment by bsthinker** [comment]
I tried the museum data set and the household data set and am unable to work with either of those.

Same program, but pointing to musesum.mdd and ddf produces the following error.
C:\Users\brent\Anaconda3\envs\qp\lib\site-packages\pandas\tools\merge.py:536: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    meta, data = read_dimensions("Museum.mdd", "Museum.ddf")
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\io.py", line 296, in read_dimensions
    meta, data = quantipy_from_dimensions(path_mdd, path_ddf)
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\dimensions\reader.py", line 897, in quantipy_from_dimensions
    meta, ddf = mdd_to_quantipy(path_mdd, data=L1)
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\dimensions\reader.py", line 680, in mdd_to_quantipy
    meta, columns, data = get_columns_meta(xml, meta, data, map_values=True)
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\dimensions\reader.py", line 639, in get_columns_meta
    column = begin_column(xml, col_name, data)
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\dimensions\reader.py", line 446, in begin_column
    var = xml.xpath(xpath_var)[0]
IndexError: list index out of range

For the household data set I get the following error.

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    meta, data = read_dimensions("household.mdd", "household.ddf")
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\io.py", line 296, in read_dimensions
    meta, data = quantipy_from_dimensions(path_mdd, path_ddf)
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\dimensions\reader.py", line 886, in quantipy_from_dimensions
    force_single=True)
  File "c:\users\brent\quantipy\quantipy\core\tools\dp\dimensions\reader.py", line 278, in as_L1
    child = child.join(parent_level_id[level_id])
  File "C:\Users\brent\Anaconda3\envs\qp\lib\site-packages\pandas\core\frame.py", line 4555, in join
    rsuffix=rsuffix, sort=sort)
  File "C:\Users\brent\Anaconda3\envs\qp\lib\site-packages\pandas\core\frame.py", line 4569, in _join_compat
    suffixes=(lsuffix, rsuffix), sort=sort)
  File "C:\Users\brent\Anaconda3\envs\qp\lib\site-packages\pandas\tools\merge.py", line 62, in merge
    return op.get_result()
  File "C:\Users\brent\Anaconda3\envs\qp\lib\site-packages\pandas\tools\merge.py", line 556, in get_result
    rdata.items, rsuf)
  File "C:\Users\brent\Anaconda3\envs\qp\lib\site-packages\pandas\core\internals.py", line 4699, in items_overlap_with_suffix
    to_rename)
ValueError: columns overlap but no suffix specified: Index([u'LevelId'], dtype='object', name=u'column')

**Comment by bsthinker** [comment]
BTW, if the error message about 
if parent =='None' is the point of failure, then I would think you would want something like
if parent.any()=='None' 
fwiw.

I appreciate your looking into this.

**Comment by alextanski** [comment]
Thanks for double-checking. These are the Dimensions docs. example datasets, right? I guess we must have them somewhere as well. We'll investigate what's going wrong here.

As for for the `develop` branch, easiest would be: You can either use a version control tool as SourceTree (with a UI) or the gitbash command line to checkout the develop branch. You could also simply switch to the `develop` branch in GitHub, download the zipped lib folder and then simply copy over the folders/files into your current installation:
 
![image](https://user-images.githubusercontent.com/13119448/37892585-8c5c5984-30d8-11e8-8e54-1f35f456ed92.png)

**Comment by bsthinker** [comment]
I downloaded the develop branch and  now only get one error message. Which appears to be progress.  But I still can't read dimensions.

(qp) brent@brent-Blade-Stealth:~/DDF$ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    meta, data = qp.read_dimensions('household.mdd', 'household.ddf')
  File "/home/brent/quantipy/quantipy/quantipy/core/tools/dp/io.py", line 296, in read_dimensions
    meta, data = quantipy_from_dimensions(path_mdd, path_ddf)
  File "/home/brent/quantipy/quantipy/quantipy/core/tools/dp/dimensions/reader.py", line 858, in quantipy_from_dimensions
    ddf, levels = quantipy_clean(ddf_to_pandas(path_ddf))
  File "/home/brent/quantipy/quantipy/quantipy/core/tools/dp/dimensions/reader.py", line 70, in ddf_to_pandas
    "The 'Levels' table was not found. Your DDF may be empty"
KeyError: "The 'Levels' table was not found. Your DDF may be empty or corrupt."

**Comment by alextanski** [comment]
Right, thank you. We're currently a bit busy solving some production critical  requests but will try to investigate it this week. Will keep you posted!
